version: '3.8'

services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: desafio-db
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "Numsey#2021"
      MSSQL_PID: "Developer"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./script\ Db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "1433:1433"
    networks:
      - desafio_api-network

  # .NET API
  desafio_api:
    image: italopessan/desafio_tecnico.api:latest
    container_name: desafio-api
    build:
      context: .
      dockerfile: Desafio_Tecnico/Desafio_Tecnico.Api/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=desafio_tecnico;User Id=sa;Password=Numsey#2021;TrustServerCertificate=True"
    ports:
      - "5500:80"
    depends_on:
      - sqlserver
    networks:
      - desafio_api-network
    restart: unless-stopped

  # Angular Frontend
  frontend:
    image: italopessan/desafio_tecnico.app:latest
    container_name: desafio-front
    build:
      context: ./Desafio_Tecnico.App
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - desafio_api
    networks:
      - desafio_api-network
    restart: unless-stopped
    environment:
      - API_URL=http://desafio_api:80

networks:
  desafio_api-network:
    driver: bridge

volumes:
  mssql_data:
    driver: local
