name: .NET

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Desafio_Tecnico

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore Desafio_Tecnico.slnx

      - name: Build
        run: dotnet build Desafio_Tecnico.slnx --configuration Release --no-restore

      - name: Test
        run: dotnet test Desafio_Tecnico.slnx --configuration Release --no-build --verbosity normal
